server.port=8000
spring.application.name=api-gateway

# Discovery Config
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Auth Route
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://sb
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# Products Route
spring.cloud.gateway.routes[1].id=products-service
spring.cloud.gateway.routes[1].uri=http://php:80
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/products/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/products(?<segment>/?.*), ${segment}

# Checkout Route
spring.cloud.gateway.routes[2].id=checkout-service
spring.cloud.gateway.routes[2].uri=http://django:8000
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/checkout/**, /api/orders/**

# Eureka Config
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

# JWT Secret (shared across all services)
jwt.secret=Zm9ydHktdHdvLWlzLXRoZS1hbnN3ZXItdG8tbGlmZS10aGUtdW5pdmVyc2UtYW5kLWV2ZXJ5dGhpbmc=
